# DO NOT DELETE

core.o: core.h memory.h node.h variable.h object.h position.h types.h
core.o: simple_types.h functions.h typeContainer.h
functions.o: functions.h node.h variable.h object.h position.h types.h
functions.o: simple_types.h
help_functions.o: help_functions.h
instructions.o: instructions.h node.h variable.h object.h position.h types.h
instructions.o: simple_types.h core.h memory.h functions.h typeContainer.h
instructions.o: help_functions.h
memory.o: memory.h node.h variable.h object.h position.h types.h
memory.o: simple_types.h
node.o: node.h variable.h object.h position.h types.h simple_types.h
parser_classes.o: parser_classes.h instructions.h node.h variable.h object.h
parser_classes.o: position.h types.h simple_types.h core.h memory.h
parser_classes.o: functions.h typeContainer.h help_functions.h
parser_functions.o: ./parser_functions.h ./lval.h position.h enums.h
parser_functions.o: parser_classes.h instructions.h node.h variable.h
parser_functions.o: object.h types.h simple_types.h core.h memory.h
parser_functions.o: functions.h typeContainer.h help_functions.h
position.o: position.h
targets.o: targets.h position.h
tree.o: tree.h node.h variable.h object.h position.h types.h simple_types.h
typeContainer.o: typeContainer.h types.h
types.o: types.h
variable.o: variable.h object.h position.h types.h simple_types.h
